 { pkgs, inputs, hostName, ipv6Address ? null, lib, ... }:
 
 {
   nix.settings = {
     experimental-features = "nix-command flakes";
   };
   
   environment.systemPackages = with inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system}; [
     pkgs.vim
     pkgs.git
     pkgs.dig
     pkgs.tmux
     pi
     claude-code
   ];
   
   # Mounts are kept here (rather than generated by disko) so a `nixos-rebuild
  # switch` never changes how the running hosts mount. disko (./disko.nix) owns
  # partitioning/formatting and creates matching labels for from-scratch installs.
  fileSystems."/" = {
     device = "/dev/disk/by-label/nixos";
     fsType = "ext4";
   };
   fileSystems."/boot" = {
     device = "/dev/disk/by-label/boot";
     fsType = "ext4";
   };
   swapDevices = [
     {
       device = "/dev/disk/by-label/swap";
     }
   ];
   
   environment.variables.EDITOR = "vim";

   time.timeZone = "Europe/London";
   i18n.defaultLocale = "en_US.UTF-8";
   console.keyMap = "us";
   
   boot.loader.grub.enable = true;
   boot.loader.grub.device = "/dev/sda";
   boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" "ext4" ];
   
   programs.fish.enable = true;
   programs.git.enable = true;
   programs.git.config = {
     user.name = "Jason Larigakis";
     user.email = "jason@thessaly.ca";
   };

   users.users = {
     root.hashedPassword = "!"; # Disable root login
     jason = {
       shell = pkgs.fish;
       isNormalUser = true;
       extraGroups = [ "wheel" ];
       openssh.authorizedKeys.keys = [
         "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPU92o3L1QfGpd4zSIKGkm/7xocib4q2icrbxBudZZnZ jason@thessaly.ca"
       ];
     };
   };
   
   security.sudo.wheelNeedsPassword = false;
   
   services.openssh = {
     enable = true;
     settings = {
       PermitRootLogin = "no";
       PasswordAuthentication = false;
       KbdInteractiveAuthentication = false;
     };
   };
   
   networking.hostName = hostName;
   networking.domain = "jlar.eu";
   networking.firewall.allowedTCPPorts = [ 22 ];

   # IPv6: statically assign the ::1 of this host's Hetzner /64, mirroring what
   # Ubuntu's cloud-init configures from the Hetzner metadata service. The /64
   # is on-link and the gateway is the link-local fe80::1.
   networking.useDHCP = true;
   networking.interfaces.enp1s0.ipv6.addresses =
     lib.optional (ipv6Address != null) {
       address = ipv6Address;
       prefixLength = 64;
     };
   networking.defaultGateway6 = lib.optionalAttrs (ipv6Address != null) {
     address = "fe80::1";
     interface = "enp1s0";
   };
   networking.nameservers = [
     "185.12.64.2" "185.12.64.1"
     "2a01:4ff:ff00::add:2" "2a01:4ff:ff00::add:1"
   ];
   
   system.stateVersion = "24.11";
 }
