 { pkgs, inputs, hostName, ipv6Address ? null, lib, ... }:
 
 {
   nix.settings = {
     experimental-features = "nix-command flakes";
   };
   
   environment.systemPackages = with inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system}; [
     pkgs.vim
     pkgs.git
     pkgs.dig
     pkgs.tmux
     pi
     claude-code
   ];
   
   # Mount points (fileSystems."/", fileSystems."/boot", swapDevices) are now
   # generated by disko from ./disko.nix, so they are no longer declared here.
   
   environment.variables.EDITOR = "vim";

   time.timeZone = "Europe/London";
   i18n.defaultLocale = "en_US.UTF-8";
   console.keyMap = "us";
   
   boot.loader.grub.enable = true;
   boot.loader.grub.device = "/dev/sda";
   boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" "ext4" ];
   
   programs.fish.enable = true;
   programs.command-not-found.enable = false;
   programs.git.enable = true;
   programs.git.config = {
     user.name = "Jason Larigakis";
     user.email = "jason@thessaly.ca";
   };

   users.users = {
     root.hashedPassword = "!"; # Disable root login
     jason = {
       shell = pkgs.fish;
       isNormalUser = true;
       extraGroups = [ "wheel" ];
       openssh.authorizedKeys.keys = [
         "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPU92o3L1QfGpd4zSIKGkm/7xocib4q2icrbxBudZZnZ jason@thessaly.ca"
       ];
     };
   };
   
   security.sudo.wheelNeedsPassword = false;
   
   services.openssh = {
     enable = true;
     settings = {
       PermitRootLogin = "no";
       PasswordAuthentication = false;
       KbdInteractiveAuthentication = false;
     };
   };
   
   # Accept gitlab.com's host key system-wide so the clones below don't
  # prompt (the first clone as jason would otherwise fail interactively).
  programs.ssh.knownHosts = {
    gitlab = {
      hostNames = [ "gitlab.com" ];
      publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp9BtnZncEOlyFXMULnE";
    };
  };

  # Clone GitLab repos into jason's home on boot if not already present.
  # Runs as jason so ownership is correct; only clones when the directory
  # is missing, so existing working trees are never clobbered. Requires that
  # the jason user has an SSH key authorised on GitLab for these repos.
  systemd.services.gitlab-clones = {
    description = "Clone gitlab repos into jason's home";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      User = "jason";
      Group = "users";
    };
    script = ''
      set -eu
      clone_if_missing() {
        local url="$1" dest="$2"
        if [ ! -d "$dest" ]; then
          mkdir -p /home/jason/okra/
          ${pkgs.git}/bin/git clone "$url" "$dest"
        fi
      }
      clone_if_missing "git@gitlab.com:okrasolar/cloud/okra-apollo.git" "/home/jason/okra/apollo"
      clone_if_missing "git@gitlab.com:okrasolar/cloud/harvest-alpha.git" "/home/jason/okra/harvest"
      clone_if_missing "git@gitlab.com:okrasolar/cloud/okra-etl.git" "/home/jason/okra/etl"
      clone_if_missing "git@gitlab.com:okrasolar/firmware/beacon-v2-installer.git" "/home/jason/okra/beacon"
      clone_if_missing "git@gitlab.com:okrasolar/cloud/cloud-infrastructure-as-code-cdk.git" "/home/jason/okra/cdk"
    '';
  };

  networking.hostName = hostName;
   networking.domain = "jlar.eu";
   networking.firewall.allowedTCPPorts = [ 22 ];

   # IPv6: statically assign the ::1 of this host's Hetzner /64, mirroring what
   # Ubuntu's cloud-init configures from the Hetzner metadata service. The /64
   # is on-link and the gateway is the link-local fe80::1.
   networking.useDHCP = true;
   networking.interfaces.enp1s0.ipv6.addresses =
     lib.optional (ipv6Address != null) {
       address = ipv6Address;
       prefixLength = 64;
     };
   networking.defaultGateway6 = lib.optionalAttrs (ipv6Address != null) {
     address = "fe80::1";
     interface = "enp1s0";
   };
   networking.nameservers = [
     "185.12.64.2" "185.12.64.1"
     "2a01:4ff:ff00::add:2" "2a01:4ff:ff00::add:1"
   ];
   
   system.stateVersion = "24.11";
 }
